import { InternshipOffer } from "./scrapers/types";

export const DUMMY_OFFERS: InternshipOffer[] = [
  {
    id: "dummy-1",
    title: "Stage PFE Développement Fullstack React/Node.js",
    company: "TechNova Morocco",
    location: "Casablanca",
    url: "#",
    dateStr: "Aujourd'hui",
    source: "Verified",
    language: "FR",
    contract: "Sur site",
    tags: ["React", "Node.js", "MongoDB"],
  },
  {
    id: "dummy-2",
    title: "Stagiaire Développeur Mobile Flutter",
    company: "AppMinds",
    location: "Rabat",
    url: "#",
    dateStr: "Hier",
    source: "Verified",
    language: "FR",
    contract: "Télétravail",
    tags: ["Flutter", "Dart", "Firebase"],
  },
  {
    id: "dummy-3",
    title: "Stage Data Engineer / Python",
    company: "DataCloud Services",
    location: "Tangier",
    url: "#",
    dateStr: "Il y a 2 jours",
    source: "Verified",
    language: "EN",
    contract: "Télétravail",
    tags: ["Python", "Spark", "SQL"],
  },
  {
    id: "dummy-4",
    title: "Stagiaire Backend PHP / Laravel",
    company: "WebFlow Solutions",
    location: "Marrakech",
    url: "#",
    dateStr: "Il y a 3 jours",
    source: "Verified",
    language: "FR",
    contract: "Sur site",
    tags: ["PHP", "Laravel", "MySQL"],
  },
  {
    id: "dummy-5",
    title: "Stage Frontend Vue.js / Tailwind",
    company: "Pixel Studio",
    location: "Fès",
    url: "#",
    dateStr: "Il y a 1 jour",
    source: "Verified",
    language: "FR",
    contract: "Sur site",
    tags: ["Vue.js", "Tailwind CSS", "JavaScript"],
  },
  {
    id: "dummy-6",
    title: "Stage DevOps & Cloud (AWS/Docker)",
    company: "CloudNative",
    location: "Casablanca",
    url: "#",
    dateStr: "Hier",
    source: "Verified",
    language: "EN",
    contract: "Sur site",
    tags: ["Docker", "AWS", "CI/CD"],
  },
  {
    id: "dummy-7",
    title: "Stagiaire Développeur Java / Spring Boot",
    company: "Enterprise Logic",
    location: "Rabat",
    url: "#",
    dateStr: "Il y a 4 jours",
    source: "Verified",
    language: "FR",
    contract: "Sur site",
    tags: ["Java", "Spring Boot", "PostgreSQL"],
  },
  {
    id: "dummy-8",
    title: "Stage UI/UX Design & Intégration",
    company: "Creative Lab",
    location: "Agadir",
    url: "#",
    dateStr: "Il y a 2 jours",
    source: "Verified",
    language: "FR",
    contract: "Télétravail",
    tags: ["Figma", "CSS", "HTML"],
  },
  {
    id: "dummy-9",
    title: "Stage Intelligence Artificielle / ML",
    company: "Future AI",
    location: "Casablanca",
    url: "#",
    dateStr: "Il y a 3 jours",
    source: "Verified",
    language: "EN",
    contract: "Sur site",
    tags: ["Python", "PyTorch", "OpenCV"],
  },
  {
    id: "dummy-10",
    title: "Stagiaire Pentest / Cybersécurité",
    company: "Shield Cyber",
    location: "Rabat",
    url: "#",
    dateStr: "Il y a 5 jours",
    source: "Verified",
    language: "FR",
    contract: "Sur site",
    tags: ["Kali Linux", "Burp Suite", "Networking"],
  },
  {
    id: "dummy-11",
    title: "Stage .NET Core / C# Backend",
    company: "Core Systems",
    location: "Tangier",
    url: "#",
    dateStr: "Il y a 6 jours",
    source: "Verified",
    language: "FR",
    contract: "Sur site",
    tags: [".NET", "C#", "SQL Server"],
  },
  {
    id: "dummy-12",
    title: "Stage Développeur Blockchain / Solidity",
    company: "Web3 Innovation",
    location: "Casablanca",
    url: "#",
    dateStr: "Hier",
    source: "Verified",
    language: "EN",
    contract: "Télétravail",
    tags: ["Solidity", "Ethereum", "Ethers.js"],
  },
];
