import { JobListing } from "@/lib/types";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_JOBS: JobListing[] = [
  // BATCH 1 (12 Items)
  {
    id: "mock-1",
    title: "Stage Fullstack React/Node.js",
    company: "DevSolutions Morocco",
    location: "Casablanca",
    contractType: "hybrid",
    postedAt: hoursAgo(5),
    description: "Nous recherchons un stagiaire passionné par le développement Web MERN Stack pour rejoindre notre équipe agile.",
    url: "https://example.com/apply-1",
    source: "Stage.ma",
    language: "fr",
    stack: ["React", "Node.js", "MongoDB", "Express"],
    isNew: true,
  },
  {
    id: "mock-2",
    title: "Internship: Machine Learning & Python",
    company: "DataLogic Rabat",
    location: "Rabat",
    contractType: "onsite",
    postedAt: hoursAgo(24),
    description: "Join our data science team to work on real-world NLP and predictive maintenance models.",
    url: "https://example.com/apply-2",
    source: "Rekrute",
    language: "en",
    stack: ["Python", "TensorFlow", "Pandas", "Scikit-Learn"],
    isNew: true,
  },
  {
    id: "mock-3",
    title: "Stage Développeur Mobile (Flutter)",
    company: "AppMaster Tangier",
    location: "Tangier",
    contractType: "remote",
    postedAt: daysAgo(2),
    description: "Stage PFE pour la création d'une application e-commerce multi-plateforme.",
    url: "https://example.com/apply-3",
    source: "Khdma.ma",
    language: "fr",
    stack: ["Flutter", "Dart", "Firebase"],
    isNew: false,
  },
  {
    id: "mock-4",
    title: "Cloud Infrastructure Intern",
    company: "Nexus Cloud",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(12),
    description: "Work on AWS/Azure migration projects for enterprise clients in Morocco.",
    url: "https://example.com/apply-4",
    source: "Indeed",
    language: "en",
    stack: ["AWS", "Terraform", "Docker", "Kubernetes"],
    isNew: true,
  },
  {
    id: "mock-5",
    title: "Stage Laravel / Vue.js",
    company: "WebElite Marrakesh",
    location: "Marrakech",
    contractType: "hybrid",
    postedAt: daysAgo(3),
    description: "Maintenance et évolution d'une plateforme SaaS locale.",
    url: "https://example.com/apply-5",
    source: "Emploi.ma",
    language: "fr",
    stack: ["PHP", "Laravel", "Vue.js", "MySQL"],
    isNew: false,
  },
  {
    id: "mock-6",
    title: "CyberSecurity Analyst Intern",
    company: "SecureNet Casa",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(3),
    description: "Monitoring SIEM events and performing vulnerability assessment.",
    url: "https://example.com/apply-6",
    source: "MarocAnnonces",
    language: "en",
    stack: ["Security", "SIEM", "Linux", "Python"],
    isNew: true,
  },
  {
    id: "mock-7",
    title: "Stage UI/UX Design",
    company: "CreativeHub Rabat",
    location: "Rabat",
    contractType: "remote",
    postedAt: daysAgo(4),
    description: "Conception de maquettes haute fidélité sur Figma pour des startups.",
    url: "https://example.com/apply-7",
    source: "Rekrute",
    language: "fr",
    stack: ["Figma", "UI/UX", "Adobe Suite"],
    isNew: false,
  },
  {
    id: "mock-8",
    title: "DevOps Engineering Intern",
    company: "AgileOps Morocco",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(1),
    description: "CI/CD pipeline automation using Jenkins and GitLab CI.",
    url: "https://example.com/apply-8",
    source: "Indeed",
    language: "en",
    stack: ["Docker", "Jenkins", "Ansible", "Git"],
    isNew: true,
  },
  {
    id: "mock-9",
    title: "Stage Java / Spring Boot",
    company: "FinTech Solutions",
    location: "Casablanca",
    contractType: "hybrid",
    postedAt: hoursAgo(20),
    description: "Développement de services backend pour une application bancaire.",
    url: "https://example.com/apply-9",
    source: "Emploi.ma",
    language: "fr",
    stack: ["Java", "Spring Boot", "PostgreSQL"],
    isNew: true,
  },
  {
    id: "mock-10",
    title: "Software QA Automation Intern",
    company: "TestGenius Rabat",
    location: "Rabat",
    contractType: "onsite",
    postedAt: daysAgo(6),
    description: "Automation of regression testing using Selenium and Cypress.",
    url: "https://example.com/apply-10",
    source: "Khdma.ma",
    language: "en",
    stack: ["Selenium", "Cypress", "JavaScript"],
    isNew: false,
  },
  {
    id: "mock-11",
    title: "Stage Big Data (Hadoop/Spark)",
    company: "DataMasters Casa",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(6),
    description: "Analyse de grands volumes de données pour le secteur télécom.",
    url: "https://example.com/apply-11",
    source: "Stage.ma",
    language: "fr",
    stack: ["Spark", "Scala", "Hadoop"],
    isNew: true,
  },
  {
    id: "mock-12",
    title: "Stage Frontend developer (Next.js)",
    company: "WebCraft Solutions",
    location: "Tangier",
    contractType: "remote",
    postedAt: hoursAgo(2),
    description: "Join our frontend team working on modern Next.js 15 apps.",
    url: "https://example.com/apply-12",
    source: "Rekrute",
    language: "en",
    stack: ["Next.js", "React", "Tailwind CSS"],
    isNew: true,
  },

  // BATCH 2 (12 Items)
  {
    id: "mock-13",
    title: "Stage Angular Développeur",
    company: "DigitalBridge Casa",
    location: "Casablanca",
    contractType: "hybrid",
    postedAt: daysAgo(3),
    description: "Développement d'interfaces dashboard complexes avec Angular 17.",
    url: "https://example.com/apply-13",
    source: "MarocAnnonces",
    language: "fr",
    stack: ["Angular", "TypeScript", "RxJS"],
    isNew: false,
  },
  {
    id: "mock-14",
    title: "Golang Backend Intern",
    company: "CloudNative Rabat",
    location: "Rabat",
    contractType: "onsite",
    postedAt: hoursAgo(8),
    description: "Building high-performance microservices in Go.",
    url: "https://example.com/apply-14",
    source: "M-Job",
    language: "en",
    stack: ["Go", "gRPC", "Docker"],
    isNew: true,
  },
  {
    id: "mock-15",
    title: "Stage PHP / Symfony",
    company: "TechnoPoles",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: daysAgo(2),
    description: "Optimisation de sites e-commerce sous Symfony 6.",
    url: "https://example.com/apply-15",
    source: "OptionCarriere",
    language: "fr",
    stack: ["PHP", "Symfony", "SQLite"],
    isNew: false,
  },
  {
    id: "mock-16",
    title: "iOS Development Intern",
    company: "MobileFirst Agadir",
    location: "Agadir",
    contractType: "remote",
    postedAt: hoursAgo(30),
    description: "Swift development for innovative native iOS applications.",
    url: "https://example.com/apply-16",
    source: "Stage.ma",
    language: "en",
    stack: ["Swift", "SwiftUI", "Combine"],
    isNew: true,
  },
  {
    id: "mock-17",
    title: "Stage Intelligence Artificielle",
    company: "AILab Casablanca",
    location: "Casablanca",
    contractType: "hybrid",
    postedAt: hoursAgo(4),
    description: "Exploration de modèles LLM et intégration via API.",
    url: "https://example.com/apply-17",
    source: "Rekrute",
    language: "fr",
    stack: ["Python", "OpenAI", "LangChain"],
    isNew: true,
  },
  {
    id: "mock-18",
    title: "Blockchain Intern",
    company: "CryptoMaroc",
    location: "Rabat",
    contractType: "onsite",
    postedAt: daysAgo(5),
    description: "Smart contract development on Ethereum/Polygon.",
    url: "https://example.com/apply-18",
    source: "Indeed",
    language: "en",
    stack: ["Solidity", "Web3.js", "Ethereum"],
    isNew: false,
  },
  {
    id: "mock-19",
    title: "Stage .NET Core / C#",
    company: "EuroSystem Morocco",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(16),
    description: "Web API development for industrial management systems.",
    url: "https://example.com/apply-19",
    source: "Emploi.ma",
    language: "fr",
    stack: [".NET", "C#", "SQL Server"],
    isNew: true,
  },
  {
    id: "mock-20",
    title: "Salesforce Admin Intern",
    company: "CloudCRM",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: daysAgo(8),
    description: "Configuration and administration of Salesforce for local NGOs.",
    url: "https://example.com/apply-20",
    source: "Khdma.ma",
    language: "en",
    stack: ["Salesforce", "Apex"],
    isNew: false,
  },
  {
    id: "mock-21",
    title: "Stage Data Analyst",
    company: "Insight Data",
    location: "Rabat",
    contractType: "hybrid",
    postedAt: hoursAgo(7),
    description: "Extraction et visualisation de données métier sur PowerBI.",
    url: "https://example.com/apply-21",
    source: "Stage.ma",
    language: "fr",
    stack: ["SQL", "PowerBI", "Excel"],
    isNew: true,
  },
  {
    id: "mock-22",
    title: "Game Developer Intern (Unity)",
    company: "Pixel Studio Casa",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(40),
    description: "C# script development for mobile hypercasual games.",
    url: "https://example.com/apply-22",
    source: "Rekrute",
    language: "en",
    stack: ["Unity", "C#", "Blender"],
    isNew: true,
  },
  {
    id: "mock-23",
    title: "Stage Marketing Digital IT",
    company: "TechPromo",
    location: "Fes",
    contractType: "remote",
    postedAt: daysAgo(12),
    description: "Gestion des réseaux sociaux et SEO pour une boîte de dev.",
    url: "https://example.com/apply-23",
    source: "Emploi.ma",
    language: "fr",
    stack: ["SEO", "Google Ads", "Canva"],
    isNew: false,
  },
  {
    id: "mock-24",
    title: "Support It Intern",
    company: "GlobalIT Support",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(11),
    description: "Internal IT infrastructure maintenance and user support.",
    url: "https://example.com/apply-24",
    source: "Indeed",
    language: "en",
    stack: ["Windows Server", "Networking", "Linux"],
    isNew: true,
  },

  // BATCH 3 (12 Items)
  {
    id: "mock-25",
    title: "Stage Node.js Serverless",
    company: "CloudLab Casa",
    location: "Casablanca",
    contractType: "remote",
    postedAt: daysAgo(2),
    description: "Développement de fonctions Lambda AWS sécurisées.",
    url: "https://example.com/apply-25",
    source: "OptionCarriere",
    language: "fr",
    stack: ["Node.js", "Serverless", "AWS"],
    isNew: false,
  },
  {
    id: "mock-26",
    title: "Ruby on Rails Intern",
    company: "StartupHaus Rabat",
    location: "Rabat",
    contractType: "hybrid",
    postedAt: hoursAgo(9),
    description: "Maintenance of an e-learning platform in Rails 7.",
    url: "https://example.com/apply-26",
    source: "MarocAnnonces",
    language: "en",
    stack: ["Ruby", "Rails", "Hotwire"],
    isNew: true,
  },
  {
    id: "mock-27",
    title: "Stage Python / Django",
    company: "WebSol Morocco",
    location: "Kenitra",
    contractType: "onsite",
    postedAt: daysAgo(3),
    description: "Création d'un portail client personnalisé.",
    url: "https://example.com/apply-27",
    source: "M-Job",
    language: "fr",
    stack: ["Python", "Django", "JavaScript"],
    isNew: false,
  },
  {
    id: "mock-28",
    title: "Embedded Systems Intern",
    company: "IoT Maroc",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(13),
    description: "C/C++ development for ESP32 and Arduino sensors.",
    url: "https://example.com/apply-28",
    source: "Stage.ma",
    language: "en",
    stack: ["C", "C++", "IoT", "MQTT"],
    isNew: true,
  },
  {
    id: "mock-29",
    title: "Stage Développeur Flutter",
    company: "AppScale Casablanca",
    location: "Casablanca",
    contractType: "hybrid",
    postedAt: hoursAgo(18),
    description: "Développement d'une application de livraison.",
    url: "https://example.com/apply-29",
    source: "Rekrute",
    language: "fr",
    stack: ["Flutter", "Dart", "Google Maps API"],
    isNew: true,
  },
  {
    id: "mock-30",
    title: "Computer Vision Intern",
    company: "SmartVision Rabat",
    location: "Rabat",
    contractType: "onsite",
    postedAt: daysAgo(16),
    description: "Object detection using YOLOv8 for industrial automation.",
    url: "https://example.com/apply-30",
    source: "Khdma.ma",
    language: "en",
    stack: ["PyTorch", "OpenCV", "Python"],
    isNew: false,
  },
  {
    id: "mock-31",
    title: "Stage WordPress / SEO",
    company: "DigitalAgency",
    location: "Marrakech",
    contractType: "remote",
    postedAt: hoursAgo(22),
    description: "Optimisation technique WordPress pour clients internationaux.",
    url: "https://example.com/apply-31",
    source: "Emploi.ma",
    language: "fr",
    stack: ["WordPress", "SEO", "PHP"],
    isNew: true,
  },
  {
    id: "mock-32",
    title: "Rust Developer Intern",
    company: "SafeCode Systems",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: hoursAgo(15),
    description: "Learning memory safety and systems programming in Rust.",
    url: "https://example.com/apply-32",
    source: "Indeed",
    language: "en",
    stack: ["Rust", "Wasm"],
    isNew: true,
  },
  {
    id: "mock-33",
    title: "Stage Testing Manuel / QA",
    company: "QualityCheck Casa",
    location: "Casablanca",
    contractType: "onsite",
    postedAt: daysAgo(3),
    description: "Exécution de plans de tests et remontée de bugs sur Jira.",
    url: "https://example.com/apply-33",
    source: "OptionCarriere",
    language: "fr",
    stack: ["Test execution", "Jira", "Excel"],
    isNew: false,
  },
  {
    id: "mock-34",
    title: "Big Data Governance Intern",
    company: "DataTrust Rabat",
    location: "Rabat",
    contractType: "onsite",
    postedAt: hoursAgo(2),
    description: "Data cataloging and quality control policies implementation.",
    url: "https://example.com/apply-34",
    source: "MarocAnnonces",
    language: "en",
    stack: ["Data Governance", "SQL", "Collibra"],
    isNew: true,
  },
  {
    id: "mock-35",
    title: "Stage Développeur Vue.js 3",
    company: "FrontMind Casablanca",
    location: "Casablanca",
    contractType: "hybrid",
    postedAt: hoursAgo(36),
    description: "Migration d'une dashboard de Vue 2 vers Vue 3 Composition API.",
    url: "https://example.com/apply-35",
    source: "M-Job",
    language: "fr",
    stack: ["Vue.js", "Pinia", "TypeScript"],
    isNew: true,
  },
  {
    id: "mock-36",
    title: "Cloud DevSecOps Intern",
    company: "SecureCloud Rabat",
    location: "Rabat",
    contractType: "onsite",
    postedAt: hoursAgo(10),
    description: "Integrating security scans into Kubernetes deployment pipes.",
    url: "https://example.com/apply-36",
    source: "Indeed",
    language: "en",
    stack: ["Docker", "Kubernetes", "Snyk", "Python"],
    isNew: true,
  },
];
